name: CI

on: [pull_request]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  basic:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('./**/*.csproj') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore

      - name: Run tests
        run: dotnet test
        env:
          STREAM_SECRET: ${{ secrets.STREAM_API_SECRET }}
          STREAM_KEY: ${{ secrets.STREAM_API_KEY }}
