name: Release

on:
  push:
    branches:
      - master

jobs:
  Release:
    if: "${{ startsWith(github.event.head_commit.message, 'chore(release)') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - uses: actions/github-script@v5
        with:
          script: |
            const get_change_log_diff = require('./scripts/get_changelog_diff.js')
            core.exportVariable('CHANGELOG', get_change_log_diff())

            // Getting the release version from the commit message
            // Commit message looks like this: chore(release): 1.0.0
            const version = context.payload.head_commit.message.split(' ')[1]
            core.exportVariable('VERSION', version)
  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Build
        run: dotnet build --configuration Release ./src

      - name: Create the package
        run: dotnet pack --configuration Release ./src

      - name: Publish the package
        run: dotnet nuget push "./src/stream-chat-net/bin/Release/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
